name: update_image

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'
  workflow_dispatch:

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  update_image:
    # Name the Job
    name: update image from bing.com everyday
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: fetch an image from bing.com
        run: ./bing-wallpaper.sh -p images
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "`date +"%Y-%m-%d"`"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
